---
title: "Colostrum Data"
author: "Susan Glenn"
date: "6/29/2020"
output: pdf_document
---

```{r}
setwd("~/Documents/Consulting/Joana, Calf graphs/Colostrum")
data <- read.csv("Colostrum.csv")
data <- data[1:129,]

##Looking for multicolinearity in coavraites
library(dplyr)
covariates <- data %>%
  select(Treat, Birth, AgeDay, AgeYear, Parity, IA, DryPeriod, DIM, DIM305, TotMilk, Calving, CalvingTime, ColWeight, Brix, IcaCalve, IcaMilk, Breed, Sex) %>%
  mutate_all(funs(as.numeric))
```

```{r}
library(corrplot)
library(RColorBrewer)
M <- cor(covariates)
corrplot(M, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))

library(car)
library(lattice)
pairs(~Treat+Birth+AgeDay+AgeYear+Parity+IA+DryPeriod+DIM+DIM305+TotMilk+Calving+CalvingTime+ColWeight+Brix+IcaCalve+IcaMilk+Breed+Sex, data=covariates, main="Correlation All covaraites")

pairs(~Birth+AgeDay+AgeYear+IA+DryPeriod+DIM+DIM305+TotMilk+Calving+CalvingTime+ColWeight+Brix+IcaCalve+IcaMilk, data=covariates, main="Correlation Continous Covariates")

cor(covariates$AgeDay, covariates$AgeYear) #Anything above 0.8 or below -0.8 should be taken out
cor(data$CalfWeight, data$AgeDay)
cor(data$CalfWeight, data$AgeYear)
```

```{r}
#look at correlation for each treatment
Control <- subset(data, Treat=="Control")
control <- Control %>%
  select(Birth, AgeDay, AgeYear, Parity, IA, DryPeriod, DIM, DIM305, TotMilk, Calving, CalvingTime, ColWeight, Brix, IcaCalve, IcaMilk, Breed, Sex) %>%
  mutate_all(funs(as.numeric))

pairs(~Birth+AgeDay+AgeYear+IA+DryPeriod+DIM+DIM305+TotMilk+Calving+CalvingTime+ColWeight+Brix+IcaCalve+IcaMilk, data=control, main="Correlation Continous Covariates")
```

```{r}
##Correlation in response with covariates
weight <- data %>%
  select(CalfWeight, Cow, Treat, Birth, AgeDay, AgeYear, Parity, IA, DryPeriod, DIM, DIM305, TotMilk, Calving, CalvingTime, ColWeight, Brix, IcaCalve, IcaMilk, Breed, Sex) %>%
  mutate_all(funs(as.numeric))

M <- cor(weight)
corrplot(M, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))

pairs(~Birth+AgeDay+AgeYear+IA+DryPeriod+DIM+DIM305+TotMilk+Calving+CalvingTime+ColWeight+Brix+IcaCalve+IcaMilk, data=weight, main="Correlation Continous Covariates")

library(ggplot2)
ggplot(data, aes(x=AgeYear, y=CalfWeight, group=Treat, color=Treat)) +
  geom_point() +
  facet_grid(.~Treat) +
  geom_smooth(method = "lm", se = TRUE) +
  theme_minimal()
```

